// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL) {
  const error = 'Missing env.VITE_SUPABASE_URL. Configure as variáveis de ambiente na Vercel (Settings → Environment Variables).';
  console.error('❌ Supabase Configuration Error:', error);
  throw new Error(error);
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  const error = 'Missing env.VITE_SUPABASE_PUBLISHABLE_KEY. Configure as variáveis de ambiente na Vercel (Settings → Environment Variables).';
  console.error('❌ Supabase Configuration Error:', error);
  throw new Error(error);
}

// Validação básica do formato da URL
if (!SUPABASE_URL.startsWith('https://') || !SUPABASE_URL.includes('.supabase.co')) {
  console.warn('⚠️ Supabase URL parece estar incorreta:', SUPABASE_URL);
}

// Validação básica do formato da chave (deve começar com eyJ)
if (!SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ')) {
  console.warn('⚠️ Supabase API Key parece estar incorreta. Certifique-se de usar a anon public key.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});